-- MySQL Script generated by MySQL Workbench
-- Thu May 30 00:40:06 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema springsolidarite
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema springsolidarite
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `springsolidarite` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `springsolidarite` ;

-- -----------------------------------------------------
-- Table `springsolidarite`.`administrateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`administrateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`roles` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_bbxiq3fbrr32wfkco6ichxaly` (`nom` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`individus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`individus` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(128) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `password` VARCHAR(20) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `role_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_jpm45vronbq12v7171w8ap1fe` (`nom` ASC) VISIBLE,
  INDEX `FKdi3npx65k2n573qyy70jla30k` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKdi3npx65k2n573qyy70jla30k`
    FOREIGN KEY (`role_id`)
    REFERENCES `springsolidarite`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 11
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`administrateurs_individus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`administrateurs_individus` (
  `administrateur_id` INT NOT NULL,
  `individu_id` INT NOT NULL,
  INDEX `FKecpm9hrbqg18h9lfvcuojb1i1` (`individu_id` ASC) VISIBLE,
  INDEX `FKbnbad8wkklmmkbg8imajmah3k` (`administrateur_id` ASC) VISIBLE,
  CONSTRAINT `FKbnbad8wkklmmkbg8imajmah3k`
    FOREIGN KEY (`administrateur_id`)
    REFERENCES `springsolidarite`.`administrateurs` (`id`),
  CONSTRAINT `FKecpm9hrbqg18h9lfvcuojb1i1`
    FOREIGN KEY (`individu_id`)
    REFERENCES `springsolidarite`.`individus` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`organisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`organisateurs` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `prenom` VARCHAR(45) NOT NULL,
  `role_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_32hgp8j0f5mypknj2yrjqokih` (`nom` ASC) VISIBLE,
  INDEX `FKsi7dc7atse1yxpdpknj2ehwsi` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKsi7dc7atse1yxpdpknj2ehwsi`
    FOREIGN KEY (`role_id`)
    REFERENCES `springsolidarite`.`roles` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`administrateurs_organisateurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`administrateurs_organisateurs` (
  `administrateur_id` INT NOT NULL,
  `organisateur_id` INT NOT NULL,
  INDEX `FK6dxf1gkog3p20n4eklaosu536` (`organisateur_id` ASC) VISIBLE,
  INDEX `FK14l0ht31e7reu7m6lf77wgvjl` (`administrateur_id` ASC) VISIBLE,
  CONSTRAINT `FK14l0ht31e7reu7m6lf77wgvjl`
    FOREIGN KEY (`administrateur_id`)
    REFERENCES `springsolidarite`.`administrateurs` (`id`),
  CONSTRAINT `FK6dxf1gkog3p20n4eklaosu536`
    FOREIGN KEY (`organisateur_id`)
    REFERENCES `springsolidarite`.`organisateurs` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`associations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`associations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `nom_association` VARCHAR(90) NOT NULL,
  `password` VARCHAR(45) NOT NULL,
  `photo` VARCHAR(64) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_7xxx91po6bx7by9kd940067d2` (`nom_association` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`campagnes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`campagnes` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `fond` DOUBLE NOT NULL,
  `nom` VARCHAR(90) NOT NULL,
  `photo` VARCHAR(64) NULL DEFAULT NULL,
  `association_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_rfhoxo80tom5sjspqfc6yqtf9` (`nom` ASC) VISIBLE,
  INDEX `FK4t2ttmxpxow960qlk2jd6t81w` (`association_id` ASC) VISIBLE,
  CONSTRAINT `FK4t2ttmxpxow960qlk2jd6t81w`
    FOREIGN KEY (`association_id`)
    REFERENCES `springsolidarite`.`associations` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`associations_campagnes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`associations_campagnes` (
  `association_id` INT NOT NULL,
  `campagnes_id` INT NOT NULL,
  UNIQUE INDEX `UK_rtyelmsgfu6honbxcnk3jdhqr` (`campagnes_id` ASC) VISIBLE,
  INDEX `FKs02to80dprmigfbjae7iw5h4p` (`association_id` ASC) VISIBLE,
  CONSTRAINT `FKmn5mrmvf8fsis09bky35u1e19`
    FOREIGN KEY (`campagnes_id`)
    REFERENCES `springsolidarite`.`campagnes` (`id`),
  CONSTRAINT `FKs02to80dprmigfbjae7iw5h4p`
    FOREIGN KEY (`association_id`)
    REFERENCES `springsolidarite`.`associations` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`dons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`dons` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `financier` DOUBLE NULL DEFAULT NULL,
  `materiel` VARCHAR(254) NULL DEFAULT NULL,
  `individu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKjd7joq7jcab4qtp7roqclabru` (`individu_id` ASC) VISIBLE,
  CONSTRAINT `FKjd7joq7jcab4qtp7roqclabru`
    FOREIGN KEY (`individu_id`)
    REFERENCES `springsolidarite`.`individus` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`organisations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`organisations` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(90) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_45gvtr0vnb377eo85a8aqlbnq` (`nom` ASC) VISIBLE)
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`projets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`projets` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(255) NOT NULL,
  `nom` VARCHAR(90) NOT NULL,
  `organisation_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_41wonkjgl2g694vad33dcee15` (`nom` ASC) VISIBLE,
  INDEX `FK7s8cd2crd0jek94w0u2c86641` (`organisation_id` ASC) VISIBLE,
  CONSTRAINT `FK7s8cd2crd0jek94w0u2c86641`
    FOREIGN KEY (`organisation_id`)
    REFERENCES `springsolidarite`.`organisations` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`individus_projets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`individus_projets` (
  `individu_id` INT NOT NULL,
  `projet_id` INT NOT NULL,
  PRIMARY KEY (`individu_id`, `projet_id`),
  INDEX `FKo09vmlfksqqosw6yx25e2f0cv` (`projet_id` ASC) VISIBLE,
  CONSTRAINT `FK9wdjjaxpbap0ahdcyny08omml`
    FOREIGN KEY (`individu_id`)
    REFERENCES `springsolidarite`.`individus` (`id`),
  CONSTRAINT `FKo09vmlfksqqosw6yx25e2f0cv`
    FOREIGN KEY (`projet_id`)
    REFERENCES `springsolidarite`.`projets` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`initiative_caritative`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`initiative_caritative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(254) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `individu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UK_60txgg6lb9xt6fn76ldy45kek` (`nom` ASC) VISIBLE,
  INDEX `FK5bohidiujpvk4sljq64oo4be9` (`individu_id` ASC) VISIBLE,
  CONSTRAINT `FK5bohidiujpvk4sljq64oo4be9`
    FOREIGN KEY (`individu_id`)
    REFERENCES `springsolidarite`.`individus` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`organisateurs_projets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`organisateurs_projets` (
  `organisateur_id` INT NOT NULL,
  `projet_id` INT NOT NULL,
  INDEX `FKpgmr2c1mh6sioxl3117ay73iw` (`projet_id` ASC) VISIBLE,
  INDEX `FKcml0ub2b26u4jgvdf7o4r1dsp` (`organisateur_id` ASC) VISIBLE,
  CONSTRAINT `FKcml0ub2b26u4jgvdf7o4r1dsp`
    FOREIGN KEY (`organisateur_id`)
    REFERENCES `springsolidarite`.`organisateurs` (`id`),
  CONSTRAINT `FKpgmr2c1mh6sioxl3117ay73iw`
    FOREIGN KEY (`projet_id`)
    REFERENCES `springsolidarite`.`projets` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `springsolidarite`.`ressources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `springsolidarite`.`ressources` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `description` VARCHAR(254) NOT NULL,
  `nom` VARCHAR(45) NOT NULL,
  `individu_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK2ow64877bwbvyr20u7o1ak20w` (`individu_id` ASC) VISIBLE,
  CONSTRAINT `FK2ow64877bwbvyr20u7o1ak20w`
    FOREIGN KEY (`individu_id`)
    REFERENCES `springsolidarite`.`individus` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
